server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        - dialect: org.hibernate.dialect.MySQL57Dialect
        - dialect:
            storage_engine: innodb
  profiles:
    include: oauth,real-db
    session:
      store-type: jdbc